# Device_tracker.yaml
- platform: snmp
  host: 192.168.0.1
  community: public
  baseoid: 1.3.6.1.2.1.17.4.3.1.1
  new_device_defaults:
         track_new_devices: false
#         hide_if_away: true

#- platform: ping
#  hosts:
#    oneplus5_ping: 192.168.0.28
#    carbon_L_ping: 192.168.0.16
#    carbon_w_ping: 192.168.0.17
#  new_device_defaults:
#         track_new_devices: false
#         hide_if_away: true

- platform: mqtt
  devices:
    tinycar: 'location/tinycar'
  qos: 1
  payload_home: 'present'
  payload_not_home: 'not present'
  source_type: gps

