# Example configuration.yaml entry for the Telegram Bot
#telegram_bot:
- platform: polling
  api_key: !secret telegram_key
  allowed_chat_ids:
    - !secret telegram_chatid
#    - CHAT_ID_2
#    - CHAT_ID_3

# Example configuration.yaml entry for the notifier
#notify:
#  - name: NOTIFIER_NAME
#    platform: telegram
#    chat_id: CHAT_ID_2
