substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: garage_fan
  friendly_name: Garage Fan
  ip_address: !secret garage_fan_ip
  
esphome:
  name: $device_name
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret ssidG
  password: !secret passwdG
  manual_ip:
    static_ip: ${ip_address}
    gateway: !secret lan_gateway
    subnet: !secret lan_subnet

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

#GPIO4: Switch1, 
binary_sensor:
  - platform: gpio
    pin: 
      number: 4
      mode: INPUT_PULLUP
      inverted: true
    name: "$device_name button"
    on_press:
      - switch.toggle: relay

  - platform: status
    name: "Status"

#GPIO12: LED2i, 
switch:
  - platform: gpio
    id: red_led
    pin: 
      number: GPIO12
      inverted: true
      
  - platform: gpio
    id: blue_led
    pin: 
      number: GPIO13
      inverted: true

#GPIO14: Relay1
  - platform: gpio
    pin: GPIO14
    name: "$device_name"
    id: relay
    
#GPIO13: LED1i, 

    # Turn off red LED to show blue when turned on
    on_turn_on:
      - switch.turn_off: red_led
      - switch.turn_on: blue_led
      
    # Turns on the red LED once the plug is turned off. Stock plug doesn't do this, to restore normal behavior remove the on_turn_on and on_turn_off
    # blocks.
    on_turn_off:
      - switch.turn_on: red_led
      - switch.turn_off: blue_led
      
sensor: 
  - platform: uptime
    name: "Garage Fan Uptime" 
    
  - platform: wifi_signal
    name: "Garage Fan WiFi Signal"
    update_interval: 60s


